Second milestone: User-Interface
EdCrux/Tic-Tac-Toe-game pull request #2
Opened 2020-02-26 21:04 UTC by EdCrux

The following path for this milestone: 

We create 6 files that contain: 
- Within the View module, we have an array that keeps in the logo, a function to create new lines and a function to create a line to divide the main section of the logo
- Welcome class print the logo and a welcome message, also clear the page each time you input something.
-Names class helps to print a message to the user and store the name. 
-Board, renders the board
-Input tracks the input of each move

2020-02-27 20:16 UTC, mosesogwo requested changes
**HI @EdCrux , @mariancristu, Nice job...:clap:, but let's take care of the following:**

1. Don't edit linter config files. Undo the changes made to **.rubocop.yml** file.

2. Your `puts/prints` and `get.chomps` commands should be used in main.rb only.

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/main_rb.png)

3. You should inform the user when there is a draw or a win.

4. **Optional:** I think the suggested branch_name **user_interface** describes the branch better than **Second Milestone**. You should consider renaming the branch.

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/branch_name.png)

_**Kindly make these changes and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes requested

2020-02-27 20:16 UTC, mosesogwo commented on lib/input.rb
> +    9.times do |x|
Use a loop that terminates when there is a win or a draw instead of a fixed number of times.

2020-02-28 11:25 UTC, stratospherique requested changes
### Great progress @team :clap: However, some of the changes requested by @mosesogwo were not implemented. Check :arrow_down: 

* [x] You shouldn't edit linter config files. Undo the changes made to .rubocop.yml file.

* [ ] User Interaction related code should reside in bin folder. :pray: move code that uses puts/print get.chomp, etc. to bin folder.

### That's it :relieved: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-02-28 11:25 UTC, stratospherique commented on lib/input.rb
> +  end
```suggestion
    while game_on
      Welcome.clear
      Welcome.print_message(print, &print)
      Board.render(br_arr, &print)
      (x % 2).zero? ? action(players[0], br_arr, 'X', get_value, &print) : action(players[1], br_arr, 'O', get_value, &print)
      
      game_on = false if winner || draw
      Board.render(br_arr, &print) if x == 8
    end
  end
```

2020-02-28 21:37 UTC, Anna-Myzukina commented
## Hi team ! ! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 

# Status: [changes required]


* Good job so far, just a couple more changes and your project can be approved!


* [ ] `main.rb` uses `puts/print` and `get.chomp` commands.  From [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))![screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/main_rb.png)
## [OPTIONAL] 
Using `require_relative` for files in your directory instead of `require` is a ruby convention.

> "Require should be used for external files, like gems, while require_relative should be used for referring to files within your directory."


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png"><img class="emoji" alt="computer" height="25" width="25" src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png"></g-emoji>

2020-03-02 19:01 UTC, whiz25 approved these changes
## Congz :clap: 
You have made the requested changes and therefore it's a :+1: from me. Merge and proceed.

### Martin Afani

2020-03-02 19:23 UTC, merged